---
- hosts: eks
  tasks:
  - name: Copy springapp to eks server
    copy: src=/home/ansible/auto/springapp.yml dest=/home/eks/springapp.yml
  - name: Deploy springapp
    shell: kubectl apply -f /home/eks/springapp.yml
