- hosts: eks  
  tasks: 
    - name: copy deployment manifest files   
      copy: src=springapp.yml dest=/home/eks/springapp.yml    
    - name: deploy the web application 
      shell: kubectl apply -f /home/eks/springapp.yml 
